# default.yml
target_device: CPU
iteration: 1000
num_requests: 4

display_resolution: 1920x1080
full_screen: True

# Image data source for classification
image_source_dir: ./imagenet
image_data_extension: jpg

xml_model_path: ./public/squeezenet1.1/FP16/squeezenet1.1.xml
#xml_model_path: ./public/googlenet-v1/FP16/googlenet-v1.xml
#xml_model_path: ./public/resnet-50/FP16/resnet-50.xml
model_config:
  type: cnn   # cnn, ssd
  batch: 1
  label_file: labels_imagenet.txt

# Used by ie.setConfig() API to setup the plugin configuration
plugin_config:
  CPU:
    - CPU_THREADS_NUM: '8'
    - CPU_BIND_THREAD: 'NO'                              # NUMA, YES, NO
    - CPU_THROUGHPUT_STREAMS : '4'                        # KEY_CPU_THROUGHPUT_NUMA, KEY_CPU_THROUGHPUT_AUTO, or poritive integer
#    - KEY_ENFORCE_BF16: 'YES'                             # YES, NO
#  MYRIAD:
#    - KEY_VPU_HW_STAGES_OPTIMIZATION: 'YES'               # YES, NO
#    - KEY_VPU_COMPUTE_LAYOUT: 'VPU_AUTO'                  # VPU_AUTO, VPU_NCHW, VPU_NHWC
#  GPU:
#    - KEY_TUNING_MODE: 'TUNING_DISABLED'                  # TUNING_DIABLED, TUNING_CREATE, TUNING_EXISTING
#    - KEY_CLDNN_PLUGIN_PRIORITY: '0'                      # 0-3, 0=Disable, 3=High
#    - KEY_CLDNN_PLUGIN_THROTTLE: '0'                      # 0-3, 0=Disable, 3=High (Plugin thread priority)
#    - KEY_GPU_THROUGHPUT_STREAMS: 'GPU_THROUGHPUT_AUTO'   # GPU_THROUGHPUT_AUTO, or positive integer
#    - KEY_EXCLUSIVE_ASYNC_REQUESTS: 'NO'

# For FPS meter scaling
fps_max_value: 100

# Update screen every 'display_skip_count' inferences
display_skip_count: 10
