# default.yml
target_device: CPU
iteration: 100
num_requests: 4

display_resolution: 1920x1080
full_screen: True

# Image data source for classification
image_source_dir: ../ILSVRC2012/ILSVRC2012_img_val
image_data_extension: bmp

xml_model_path: ../../public/googlenet-v1/FP16/googlenet-v1.xml
label_file: labels_imagenet.txt

# Used by ie.setConfig() API to setup the plugin configuration
plugin_config:
  CPU:
    - CPU_THREADS_NUM: '4'
    - CPU_BIND_THREAD: 'YES'                # NUMA, YES, NO
    - CPU_THROUGHPUT_STREAMS : '4'          # KEY_CPU_THROUGHPUT_NUMA, KEY_CPU_THROUGHPUT_AUTO, or poritive integer
#    - KEY_ENFORCE_BF16: 'YES'               # YES, NO
  MYRIAD:
    - KEY_VPU_HW_STAGES_OPTIMIZATION: 'YES'   # YES, NO
    - KEY_VPU_COMPUTE_LAYOUT: 'VPU_AUTO'    # VPU_AUTO, VPU_NCHW, VPU_NHWC
  GPU:
    - KEY_TUNING_MODE: 'TUNING_DISABLED'      # TUNING_DIABLED, TUNING_CREATE, TUNING_EXISTING
    - KEY_CLDNN_PLUGIN_PRIORITY: '0'          # 0-3, 0=Disable, 3=High
    - KEY_CLDNN_PLUGIN_THROTTLE: '0'          # 0-3, 0=Disable, 3=High (Plugin thread priority)
    - KEY_GPU_THROUGHPUT_STREAMS: 'KEY_GPU_THROUGHPUT_AUTO'   # KEY_GPU_THROUGHPUT_AUTO, or positive integer
    - KEY_EXCLUSIVE_ASYNC_REQUESTS: 'NO'

# For FPS meter scaling
fps_max_value: 100

# Update screen every 'display_skip_count' inferences
display_skip_count: 5
